{% set name = "kg4vasp" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/conodipaola/kg4vasp/archive/17087e8549c772ae80df90eabf3f2cec5ab2d4d8.tar.gz
  sha256: 8811c26cc1f270e38fe214a41eaf6dd2d75955e23d367c0353b6afb5a15ce423
  patches:
    - make.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('fortran') }}

test:
  commands:
    - ${PREFIX}/bin/kg4vasp.x
    - test -f data_transport.dat
    - test -f elec_conductivity_vs_freq.dat 
  files:
    - input_parameters
    - nabla.dat
    - INPUT 

about:
  home: https://github.com/conodipaola/kg4vasp
  summary: 'Kubo-Greenwood for transport properties from First Principle Molecular Dynamics with VASP'
  description: |
    Kubo-Greenwood for transport properties from First Principle Molecular 
    Dynamics with VASP
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  doc_url: https://github.com/conodipaola/kg4vasp
  dev_url: https://github.com/conodipaola/kg4vasp

extra:
  recipe-maintainers:
    - jan-janssen
